version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'passmanager'
      MYSQL_USER: 'passapp'
      MYSQL_PASSWORD: '14550vcn23kjg90sz03gs566j'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - passmanager:/var/lib/mysql
volumes:
  passmanager: