create table if not exists user
(
    USER_ID               INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL                 VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD              CHAR(80)            NOT NULL,
    ENCRYPTED_PRIVATE_KEY VARBINARY(2048)     NOT NULL,
    PUBLIC_KEY            VARBINARY(2048)     NOT NULL
);

create table if not exists vault_role
(
    VAULT_ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME     VARCHAR(255) NOT NULL
);

create table if not exists vault
(
    VAULT_ID      INT AUTO_INCREMENT PRIMARY KEY,
    VAULT_NAME    VARCHAR(100) NOT NULL,
    VAULT_DATA    MEDIUMBLOB   NOT NULL,
    CREATED_BY    INT          NOT NULL,
    CREATED_DATE  DATETIME     NOT NULL,
    MODIFIED_BY   INT          NULL,
    MODIFIED_DATE DATETIME,
    CONSTRAINT FK_VAULT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES user (USER_ID)
) ENGINE = InnoDB;

create table if not exists vault_user
(
    VAULT_USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    VAULT_ID      INT      NOT NULL,
    USER_ID       INT      NOT NULL,
    VAULT_ROLE_ID INT      NOT NULL,
    VAULT_KEY     BLOB     NOT NULL,
    CREATED_BY    INT      NOT NULL,
    CREATED_DATE  DATETIME NOT NULL,
    MODIFIED_BY   INT NULL,
    MODIFIED_DATE DATETIME,
    UNIQUE (VAULT_ID, USER_ID),
    CONSTRAINT FK_VAULT_ROLE_ID FOREIGN KEY (VAULT_ROLE_ID) REFERENCES vault_role (VAULT_ROLE_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES user (USER_ID),
    CONSTRAINT FK_VAULT_ID FOREIGN KEY (VAULT_ID) REFERENCES vault (VAULT_ID),
    CONSTRAINT FK_VAULT_USER_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES user (USER_ID)
) ENGINE = InnoDB;